#!/usr/bin/env python3
"""Collect product commits from agentos-desktop into an auditable inventory.

The collector intentionally uses Git as the source of truth. Merge commits are
kept, but their file list is calculated against the first parent so the report
shows what the merge introduced into the AgentOS line.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path


CATEGORIES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("upstream-sync", ("merge: sync official hermes", "merge remote-tracking")),
    ("branding-i18n-policy", ("branding", "i18n", "agentos_policy.py", "prompt_builder.py", "default_soul.py")),
    ("auth-remote-gateway", ("auth", "login", "gateway", "connection-config", "ws-ticket", "remote session")),
    ("sessions-files-media-artifacts", ("session", "files", "media", "artifact", "download")),
    ("skills-hub-workflows", ("skill", "nacos", "professional-skill", "专家")),
    ("model-request-observability", ("model_request_headers", "session_id", "hermes_session_id", "relay_llm")),
    ("messaging-cron-desktop-ux", ("messaging", "cron", "statusbar", "intro", "首页", "汉化")),
    ("packaging-updater-release", ("package", "installer", "bundled-agent", "update", "dockerfile", "release", "打包", "安装")),
    ("tests-specs-governance", ("test", "docs/skills/merge-hermes-upstream", "规范", ".github/workflows")),
)


def git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout


def load_authors(path: Path) -> tuple[set[str], set[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    names: set[str] = set()
    emails: set[str] = set()
    for author in data["authors"]:
        names.update(value.casefold() for value in author.get("names", []))
        emails.update(value.casefold() for value in author.get("emails", []))
    return names, emails


def changed_files(repo: Path, commit: str, parents: list[str]) -> list[str]:
    if parents:
        output = git(repo, "diff", "--name-only", parents[0], commit)
    else:
        output = git(repo, "diff-tree", "--root", "--no-commit-id", "--name-only", "-r", commit)
    return sorted({line for line in output.splitlines() if line})


def classify(subject: str, files: list[str], parents: list[str]) -> list[str]:
    haystack = "\n".join([subject.casefold(), *(path.casefold() for path in files)])
    categories = [name for name, needles in CATEGORIES if any(needle in haystack for needle in needles)]
    if len(parents) > 1 and "upstream-sync" not in categories:
        categories.append("upstream-sync")
    return categories or ["other"]


def collect(repo: Path, branch: str, names: set[str], emails: set[str]) -> list[dict]:
    format_string = "%H%x1f%P%x1f%ad%x1f%an%x1f%ae%x1f%s%x1e"
    raw = git(repo, "log", branch, f"--format={format_string}", "--date=short")
    commits: list[dict] = []
    for record in raw.split("\x1e"):
        record = record.strip("\n")
        if not record:
            continue
        fields = record.split("\x1f")
        if len(fields) != 6:
            raise RuntimeError(f"unexpected git log record with {len(fields)} fields")
        sha, parent_text, date, name, email, subject = fields
        if name.casefold() not in names and email.casefold() not in emails:
            continue
        parents = parent_text.split() if parent_text else []
        files = changed_files(repo, sha, parents)
        commits.append(
            {
                "sha": sha,
                "shortSha": sha[:12],
                "date": date,
                "author": {"name": name, "email": email},
                "subject": subject,
                "parents": parents,
                "merge": len(parents) > 1,
                "files": files,
                "categories": classify(subject, files, parents),
            }
        )
    return commits


def markdown(branch: str, commits: list[dict], author_selection: list[dict]) -> str:
    counts = Counter(category for commit in commits for category in commit["categories"])
    lines = [
        "# AgentOS product commit inventory",
        "",
        f"Source branch: `{branch}`",
        f"Matched commits: **{len(commits)}**",
        "Author selection: " + ", ".join(
            f"`{author['github']}` (names: {', '.join(author.get('names', []))}; emails: {', '.join(author.get('emails', []))})"
            for author in author_selection
        ),
        "",
        "This file is generated by `scripts/collect_agentos_commits.py`. Merge commits are retained and compared with their first parent.",
        "",
        "## Category counts",
        "",
        "| Category | Commits |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(counts.items()))
    for category, _needles in CATEGORIES + (("other", tuple()),):
        selected = [commit for commit in commits if category in commit["categories"]]
        if not selected:
            continue
        lines.extend(["", f"## {category}", "", "| Date | Commit | Subject | Files |", "| --- | --- | --- | ---: |"])
        for commit in selected:
            subject = commit["subject"].replace("|", "\\|")
            lines.append(f"| {commit['date']} | `{commit['shortSha']}` | {subject} | {len(commit['files'])} |")
    lines.extend(["", "## Complete chronological list", ""])
    for commit in commits:
        categories = ", ".join(f"`{name}`" for name in commit["categories"])
        lines.append(f"- `{commit['shortSha']}` {commit['date']} — {commit['subject']} ({categories})")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", required=True, type=Path)
    parser.add_argument("--branch", default="agentos-20260825")
    parser.add_argument("--authors", default=Path("config/commit-authors.json"), type=Path)
    parser.add_argument("--json-out", default=Path("specs/source/agentos-20260825-commits.json"), type=Path)
    parser.add_argument("--markdown-out", default=Path("specs/source/agentos-20260825-commits.md"), type=Path)
    args = parser.parse_args()

    if not (args.repo / ".git").exists():
        parser.error(f"not a Git checkout: {args.repo}")
    author_config = json.loads(args.authors.read_text(encoding="utf-8"))
    names, emails = load_authors(args.authors)
    commits = collect(args.repo, args.branch, names, emails)
    payload = {
        "schemaVersion": 1,
        "sourceRepository": "hqzyai/agentos-desktop",
        "sourceBranch": args.branch,
        "authorSelection": author_config["authors"],
        "matchedCommitCount": len(commits),
        "commits": commits,
    }
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown_out.write_text(markdown(args.branch, commits, author_config["authors"]), encoding="utf-8")
    print(f"collected {len(commits)} commits from {args.branch}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
